### ISSUE TITLE
Symbols beginning with the characters 't', 'f' or 'n' cannot be parsed.

### ISSUE THREAD

**Issue by jcsoo** [naomijub/edn-rs#69]
```
use edn_rs::Edn;
use std::str::FromStr;

fn main() {
    let _: Edn = Edn::from_str("nTEST").unwrap();
```
results in `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseEdn("n could not be parsed")', }
src/main.rs:5:41`.

```
use edn_rs::Edn;
use std::str::FromStr;

fn main() {
    let _: Edn = Edn::from_str("tTEST").unwrap();
}
```
results in `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseEdn("provided string was not `true` or `false`")', src/main.rs:5:41`.

```
use edn_rs::Edn;
use std::str::FromStr;

fn main() {
    let _: Edn = Edn::from_str("fTEST").unwrap();
}
```
results in `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseEdn("provided string was not `true` or `false`")', src/main.rs:5:41`.

**Comment by naomijub** [comment]
Looking at this

**Comment by evaporei** [comment]
Fixed! https://github.com/naomijub/edn-rs/pull/71

You can use version `0.16.9` for the fix :blush:
